/*
 * Background Configuration - Dynamic Colors
 * Generated by Matugen
 * Updates dynamically when wallpaper/colors change
 */

import QtQuick
import Quickshell

/**
 * Background color palette dynamically injected by matugen
 * Used by shell components to maintain visual consistency
 */
Item {
    id: backgroundConfig

    // ═══════════════════════════════════════════════
    // PRIMARY COLORS - From Matugen Material Palette
    // ═══════════════════════════════════════════════

    readonly property color primary: "{{colors.primary.default.hex}}"
    readonly property color onPrimary: "{{colors.on_primary.default.hex}}"
    readonly property color primaryContainer: "{{colors.primary_container.default.hex}}"
    readonly property color onPrimaryContainer: "{{colors.on_primary_container.default.hex}}"

    // ═══════════════════════════════════════════════
    // SECONDARY COLORS
    // ═══════════════════════════════════════════════

    readonly property color secondary: "{{colors.secondary.default.hex}}"
    readonly property color onSecondary: "{{colors.on_secondary.default.hex}}"
    readonly property color secondaryContainer: "{{colors.secondary_container.default.hex}}"
    readonly property color onSecondaryContainer: "{{colors.on_secondary_container.default.hex}}"

    // ═══════════════════════════════════════════════
    // SURFACE COLORS
    // ═══════════════════════════════════════════════

    readonly property color surface: "{{colors.surface.default.hex}}"
    readonly property color onSurface: "{{colors.on_surface.default.hex}}"
    readonly property color surfaceVariant: "{{colors.surface_variant.default.hex}}"
    readonly property color onSurfaceVariant: "{{colors.on_surface_variant.default.hex}}"
    readonly property color surfaceContainer: "{{colors.surface_container.default.hex}}"
    readonly property color surfaceContainerHigh: "{{colors.surface_container_high.default.hex}}"
    readonly property color surfaceContainerHighest: "{{colors.surface_container_highest.default.hex}}"
    readonly property color surfaceContainerLow: "{{colors.surface_container_low.default.hex}}"
    readonly property color background: "{{colors.background.default.hex}}"
    readonly property color onBackground: "{{colors.on_background.default.hex}}"

    // ═══════════════════════════════════════════════
    // ERROR COLORS
    // ═══════════════════════════════════════════════

    readonly property color error: "{{colors.error.default.hex}}"
    readonly property color onError: "{{colors.on_error.default.hex}}"
    readonly property color errorContainer: "{{colors.error_container.default.hex}}"
    readonly property color onErrorContainer: "{{colors.on_error_container.default.hex}}"

    // ═══════════════════════════════════════════════
    // UTILITY COLORS
    // ═══════════════════════════════════════════════

    readonly property color outline: "{{colors.outline.default.hex}}"
    readonly property color outlineVariant: "{{colors.outline_variant.default.hex}}"
    readonly property color shadow: "{{colors.shadow.default.hex}}"
    readonly property color scrim: "{{colors.scrim.default.hex}}"
    readonly property color inverseSurface: "{{colors.inverse_surface.default.hex}}"
    readonly property color inverseOnSurface: "{{colors.inverse_on_surface.default.hex}}"
    readonly property color inversePrimary: "{{colors.inverse_primary.default.hex}}"

    // ═══════════════════════════════════════════════
    // TERTIARY (Accent Variant)
    // ═══════════════════════════════════════════════

    readonly property color tertiary: "{{colors.tertiary.default.hex}}"
    readonly property color onTertiary: "{{colors.on_tertiary.default.hex}}"
    readonly property color tertiaryContainer: "{{colors.tertiary_container.default.hex}}"
    readonly property color onTertiaryContainer: "{{colors.on_tertiary_container.default.hex}}"

    // ═══════════════════════════════════════════════
    // LEGACY BASE16 PALETTE (for terminal/compat)
    // ═══════════════════════════════════════════════

    readonly property var base16: ({
        "base00": "{{base16.base00.default.hex}}",
        "base01": "{{base16.base01.default.hex}}",
        "base02": "{{base16.base02.default.hex}}",
        "base03": "{{base16.base03.default.hex}}",
        "base04": "{{base16.base04.default.hex}}",
        "base05": "{{base16.base05.default.hex}}",
        "base06": "{{base16.base06.default.hex}}",
        "base07": "{{base16.base07.default.hex}}",
        "base08": "{{base16.base08.default.hex}}",
        "base09": "{{base16.base09.default.hex}}",
        "base0A": "{{base16.base0a.default.hex}}",
        "base0B": "{{base16.base0b.default.hex}}",
        "base0C": "{{base16.base0c.default.hex}}",
        "base0D": "{{base16.base0d.default.hex}}",
        "base0E": "{{base16.base0e.default.hex}}",
        "base0F": "{{base16.base0f.default.hex}}"
    })

    // ═══════════════════════════════════════════════
    // HELPER FUNCTIONS
    // ═══════════════════════════════════════════════

    /**
     * Get a color from base16 palette by index (0-15)
     * @param index: 0-15
     * @returns hex color string
     */
    function getBase16Color(index) {
        const keys = Object.keys(base16);
        if (index >= 0 && index < keys.length) {
            return base16[keys[index]];
        }
        return "#000000"; // Fallback
    }

    /**
     * Generate a theme-appropriate contrasting text color
     * @param bgColor: background color hex
     * @returns "white" or "black" suitable for contrast
     */
    function getTextColor(bgColor) {
        // Simple luminance calculation
        const hex = bgColor.replace("#", "");
        const r = parseInt(hex.substr(0, 2), 16);
        const g = parseInt(hex.substr(2, 2), 16);
        const b = parseInt(hex.substr(4, 2), 16);
        const luminance = (r * 299 + g * 587 + b * 114) / 1000;
        return luminance > 128 ? "black" : "white";
    }
}
