/*
 * Background Configuration - Dynamic Colors
 * Generated by Matugen
 * Updates dynamically when wallpaper/colors change
 */

import QtQuick
import Quickshell

/**
 * Background color palette dynamically injected by matugen
 * Used by shell components to maintain visual consistency
 */
Item {
    id: backgroundConfig

    // ═══════════════════════════════════════════════
    // PRIMARY COLORS - From Matugen Material Palette
    // ═══════════════════════════════════════════════

    readonly property color primary: "#814c77"
    readonly property color onPrimary: "#ffffff"
    readonly property color primaryContainer: "#ffd7f3"
    readonly property color onPrimaryContainer: "#340830"

    // ═══════════════════════════════════════════════
    // SECONDARY COLORS
    // ═══════════════════════════════════════════════

    readonly property color secondary: "#6e5868"
    readonly property color onSecondary: "#ffffff"
    readonly property color secondaryContainer: "#f8daee"
    readonly property color onSecondaryContainer: "#271624"

    // ═══════════════════════════════════════════════
    // SURFACE COLORS
    // ═══════════════════════════════════════════════

    readonly property color surface: "#fff7f9"
    readonly property color onSurface: "#201a1e"
    readonly property color surfaceVariant: "#eedee7"
    readonly property color onSurfaceVariant: "#4e444b"
    readonly property color surfaceContainer: "#f7eaf0"
    readonly property color surfaceContainerHigh: "#f2e5eb"
    readonly property color surfaceContainerHighest: "#ecdfe5"
    readonly property color surfaceContainerLow: "#fdf0f6"
    readonly property color background: "#fff7f9"
    readonly property color onBackground: "#201a1e"

    // ═══════════════════════════════════════════════
    // ERROR COLORS
    // ═══════════════════════════════════════════════

    readonly property color error: "#ba1a1a"
    readonly property color onError: "#ffffff"
    readonly property color errorContainer: "#ffdad6"
    readonly property color onErrorContainer: "#410002"

    // ═══════════════════════════════════════════════
    // UTILITY COLORS
    // ═══════════════════════════════════════════════

    readonly property color outline: "#80747b"
    readonly property color outlineVariant: "#d2c2cb"
    readonly property color shadow: "#000000"
    readonly property color scrim: "#000000"
    readonly property color inverseSurface: "#362e33"
    readonly property color inverseOnSurface: "#faedf3"
    readonly property color inversePrimary: "#f3b2e4"

    // ═══════════════════════════════════════════════
    // TERTIARY (Accent Variant)
    // ═══════════════════════════════════════════════

    readonly property color tertiary: "#815343"
    readonly property color onTertiary: "#ffffff"
    readonly property color tertiaryContainer: "#ffdbd0"
    readonly property color onTertiaryContainer: "#321207"

    // ═══════════════════════════════════════════════
    // LEGACY BASE16 PALETTE (for terminal/compat)
    // ═══════════════════════════════════════════════

    readonly property var base16: ({
        "base00": "#daccd8",
        "base01": "#c0b1be",
        "base02": "#a797a5",
        "base03": "#8d7c8b",
        "base04": "#736171",
        "base05": "#5a4758",
        "base06": "#402c3e",
        "base07": "#261224",
        "base08": "#ff7580",
        "base09": "#e0879b",
        "base0A": "#cf8bc0",
        "base0B": "#c69b00",
        "base0C": "#e38a6b",
        "base0D": "#fa65e8",
        "base0E": "#ff794a",
        "base0F": "#7a6b75"
    })

    // ═══════════════════════════════════════════════
    // HELPER FUNCTIONS
    // ═══════════════════════════════════════════════

    /**
     * Get a color from base16 palette by index (0-15)
     * @param index: 0-15
     * @returns hex color string
     */
    function getBase16Color(index) {
        const keys = Object.keys(base16);
        if (index >= 0 && index < keys.length) {
            return base16[keys[index]];
        }
        return "#000000"; // Fallback
    }

    /**
     * Generate a theme-appropriate contrasting text color
     * @param bgColor: background color hex
     * @returns "white" or "black" suitable for contrast
     */
    function getTextColor(bgColor) {
        // Simple luminance calculation
        const hex = bgColor.replace("#", "");
        const r = parseInt(hex.substr(0, 2), 16);
        const g = parseInt(hex.substr(2, 2), 16);
        const b = parseInt(hex.substr(4, 2), 16);
        const luminance = (r * 299 + g * 587 + b * 114) / 1000;
        return luminance > 128 ? "black" : "white";
    }
}
