# Generated by rice-manager.sh
export RICE_THEME="cherry"
export RICE_MODE="light"
export RICE_PALETTE="matugen-default"
export RICE_COLOR_BASE="#fff7f9"
export RICE_COLOR_TEXT="#201a1e"
export RICE_COLOR_ACCENT="#814c77"
export RICE_COLOR_URGENT="#ba1a1a"
